### ISSUE TITLE
COPY commands cached as well?

### ISSUE THREAD

**Issue by JeffJassky** [whoan/docker-build-with-cache-action#71] opened 2020-09-17 03:31 UTC
Is it expected that stages with the COPY command (IE: COPY ./ ./) will be cached as well?

My newly committed file changes were being ignored in new image builds.

**Comment by whoan** [comment] 2020-09-17 11:49
Hi @JeffJassky . Could you please elaborate on that or show me an example?
If the COPY command is cached or not, depends more on docker itself than the action.

You are claiming that you expected the cache being invalidated after the COPY command and it didn't happen? or the opposite?
If it is the former, make sure you are not ignoring the newly committed file in .dockerignore.

**Comment by whoan** [comment] 2020-09-27 11:25
Closing as no clear what the problem is. Feel free to reopen with more info. Thanks.

**Closed by whoan** 2020-09-27 11:25 UTC
