### ISSUE TITLE
image_name is substituted by my_awesome_image

### ISSUE THREAD

**Issue by anton-buyskikh** [whoan/docker-build-with-cache-action#106] opened 2022-04-19 13:21 UTC
Even though I define `image_name: my_image_name` in the workflow, the log shows that it's tagged like this:
```consol
...
Successfully tagged my_awesome_image:latest
...
```

My current solution is to add `build_extra_args: "--tag my_image_name"` which leads to the following
```consol
...
Successfully tagged my_awesome_image:latest
Successfully tagged my_image_name:latest
...
```

Is it a bug?

**Comment by matteo-rossi-wise** [comment] 2022-06-08 06:53
The issue is [here](https://github.com/whoan/docker-build-with-cache-action/blob/86b305ae784f30b8dfa1827c60c7eae37a6e00f1/docker-build.sh#L310) in the `build_image()` function. The fun fact is that I can't see the `my_awesome_image` tag in the `-stages` located images. Since this is a bit misleading I think that the `--tag` directive could be omitted if none is passed, or is it used as a default anchor to reference the specific image?

**Comment by anton-buyskikh** [comment] 2022-06-08 16:56
Yeah, the issue is that DUMMY_IMAGE_NAME is used instead of INPUT_IMAGE_TAG

**Comment by whoan** [comment] 2022-10-17 21:31
@anton-buyskikh `DUMMY_IMAGE_NAME` is used internally up to the point where it is renamed/tagged to the correct name: https://github.com/whoan/docker-build-with-cache-action/blob/7210dca924e2463bb97970841b186e824b9411a8/docker-build.sh#L102

What's the issue concern here? Is it just the log being misleading?

**Comment by anton-buyskikh** [comment] 2022-10-18 11:12
The issue 6 months ago was that `image_name` was ignored or overwritten by `my_awesome_image`
So my walk-round back then was:
```
      - name: Build image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: <username>
          password: "${{ secrets.<token> }}"
          registry: ghcr.io
          image_name: foo_name // <- this one is ignored or overwritten by $DUMMY_IMAGE_NAME
          context: .
          dockerfile: Dockerfile
          build_extra_args: "--tag foo_name" // <- without this line the image will be called my_awesome_image
```

Since it was 6 months ago, the issue might have been already resolved.

**Comment by whoan** [comment] 2022-10-20 22:20
Thanks for your answer @anton-buyskikh . I see the image correctly being renamed/tagged at the end so this is not an issue. `my_awesome_image` is used internally by the action, so although it may be misleading, I see the action creating the image with correct name.
Thanks again for your input. I am closing this one.

**Comment by anton-buyskikh** [comment] 2022-10-21 11:20
Hi @whoan, thanks for the quick reply! However, I think there is still something not quite right, I might have not explained it clearly in the first place. I'd like to know whether it's a bug or a desired feature:

If I use
```
      - name: Build image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: <username>
          password: "${{ secrets.<token> }}"
          registry: ghcr.io
          image_name: foo_name
          context: .
          dockerfile: Dockerfile
```

This action correctly creates a _package_ `ghcr.io/<username>/foo_name` (and `ghcr.io/<username>/foo_name-stages`). That's all cool!

The issue is that when the _image_ from this _package_ is pulled to the local environment of the action runner, it is not tagged as `foo_name`. It's tagged `my_awesome_image`.

I think it's a bug rather than a feature, because the docs say `image_name` and not `package_name`.

What do you think?

**Comment by whoan** [comment] 2022-10-22 20:57
Hi again @anton-buyskikh. Thanks again for your response.

Could you please clarify this sentence?:

> the image from this package

Isn't this package the same as the docker image in GitHub? I think I'm missing something. You can tag what you are building in any way and then you can (re)tag it again to the final name you want for the image. I don't remember now why I decided to use a temporary image name but I'll try to find the answer as it seems that it's generating some confusion. 

In addition, you say:

> the image from this package is pulled to the local environment of the action runner, it is not tagged as foo_nam

You can try doing a `docker pull` of any GitHub package (ie: a docker image) to your env and see what it retrieves. You shouldn't see `my_awesome_image` at all.

**Closed** 2022-10-24 17:56 UTC
Labels: help wanted
