### ISSUE TITLE
Multiple tags not working?

### ISSUE THREAD

**Issue by nloui** [whoan/docker-build-with-cache-action#56] opened 2020-07-16 15:31 UTC
I've setup my config to push multiple tags on subsequent builds:
```
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Build and push docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
          registry: docker.pkg.github.com
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          image_tag: latest,${{ github.sha }}

```

But it appears that the "latest" tag doesn't ever update.  New builds push out with the new github sha.  Am I missing something?

**Comment by whoan** [comment] 2020-07-18 23:17
Can I see some logs @nloui . How do you know doesn't ever update?

I gave it a try in a repo I have for tests and it seems it's working: https://github.com/whoan/hello-world/runs/885825489#step:4:92

**Comment by whoan** [comment] 2020-07-23 00:37
Closing as I couldn't reproduce. Feel free to open if it happens in some uncovered scenario.

**Closed by whoan** 2020-07-23 00:37 UTC
