### ISSUE TITLE
Error response from daemon: Get https://gcr.io/v2/: unknown: Unable to parse json key.

### ISSUE THREAD

**Issue by emroot** [whoan/docker-build-with-cache-action#50] opened 2020-06-10 23:56 UTC
I keep getting a parsing error `Error response from daemon: Get https://gcr.io/v2/: unknown: Unable to parse json key.`
What's the best way to store the json in github secrets?
I stored it as `'{"...":....}'`, `"{\"...\": \"...\"}"`, `{"..": ".."}` but no luck.

**Comment by whoan** [comment] 2020-06-11 11:51
@emroot I remember I had similar issue and I think it was because I was copying the json from my console. Please try openyng the json with a visual editor and copy the json from there to github secret. Don't remember well now, but I can try to reproduce later and will let you know.

**Comment by emroot** [comment] 2020-06-11 19:06
tried no luck. 
I tried the following:
entering my json key as this: `'{"...."}'`, I added the single quotes in my github secrets.
When I use your library, it doesn't work. However if I run the following:
`- run: echo ${{ secrets.GCLOUD_JSON_AUTH }} | docker login -u _json_key --password-stdin https://gcr.io` → succeeds
`- run: echo '${{ secrets.GCLOUD_JSON_AUTH }}' | docker login -u _json_key --password-stdin https://gcr.io` → fails
`- run: echo "${{ secrets.GCLOUD_JSON_AUTH }}" | docker login -u _json_key --password-stdin https://gcr.io` → fails
I'm also passing the password like this `password: ${{ secrets.GCLOUD_JSON_AUTH }}`
Tried `password: '${{ secrets.GCLOUD_JSON_AUTH }}'` and `password: "${{ secrets.GCLOUD_JSON_AUTH }}"` and both failed.
Somehow when I pass down my password to your action it fails.

**Comment by whoan** [comment] 2020-06-13 02:22
@emroot

- Didn't it work with [this change](https://github.com/emroot/docker-build-with-cache-action/commit/22675452831032a5333df26b62dfb565ad40149a#diff-b958f585a04af5ee2087610ea7180f34R157) you made?
- Are you using the action in a public repo so I can see the workflow and the action logs?
- When you save the json as a GitHub secret, in the `private_key` field, do you save `\n` or actual new lines? You should have something like `some\nprivate\nkey`
- Do you see any character in the private key which might be expanded by bash?

**Comment by whoan** [comment] 2020-06-22 21:43
Closing this for lack of information. Feel free to open if still an issue.

**Closed by whoan** 2020-06-22 21:43 UTC
